### ISSUE TITLE
Hi! I have a problem.

### ISSUE THREAD

**Issue by kubox161** [simonkeyd/bgcar#1]
sudo bgcar -i --gpu -d 1 -m 100
> Click on Store button
> Click on Recall button
> Click on Reroll button
> Click on Total roll score top left
> Click on Total roll score bottom right
Traceback (most recent call last):
  File "/usr/local/bin/bgcar", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/bgcar/cli.py", line 226, in main
    tr_maximum, roll_count = init_rolls(
  File "/usr/local/lib/python3.10/dist-packages/bgcar/cli.py", line 131, in init_rolls
    tr_value = tr_maximum = int(read_image(reader, numpy.array(tr_image))[0][1])
IndexError: list index out of range

**Comment by kubox161** [comment]
Perhaps it would be useful to add an exception handler when calling the function read_image.

For example:
while roll_count != target_roll and break_key_listener.is_alive():
        m_click(mouse_instance, buttons.reroll.position, delay)
        tr_image = grab_screen(buttons.total_roll.position)
        try:
            tr_value = int(read_image(reader, numpy.array(tr_image))[0][1])
        except ValueError:
            tr_value = 0

**Comment by simonkeyd** [comment]
hey there. I reworked the code a bit and included your suggested modification.
Regarding the error itself it usually appear when one either have a game resolution too low or when the capture zone for ` Total roll` is not precise enough. This results in easyocr being unable to read the value from the screen.
